/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Certification {
    issueDate: string;
    expiryDate: string;
    name: string;
    issuer: string;
}
export interface Skill {
    name: string;
    level: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Experience {
    endDate: string;
    description: string;
    company: string;
    jobTitle: string;
    startDate: string;
}
export interface Education {
    major: string;
    institution: string;
    graduationYear: string;
    degree: string;
}
export interface PersonalInfo {
    linkedin?: string;
    name: string;
    photoUrl?: string;
    email: string;
    summary: string;
    address: string;
    phone: string;
    github?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Project {
    title: string;
    link?: string;
    description: string;
    technologies: Array<string>;
}
export interface Resume {
    projects: Array<Project>;
    createdAt: bigint;
    education: Array<Education>;
    updatedAt: bigint;
    experiences: Array<Experience>;
    certifications: Array<Certification>;
    personalInfo: PersonalInfo;
    skills: Array<Skill>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    deleteResume(sessionToken: string): Promise<void>;
    getResume(sessionToken: string): Promise<Resume>;
    saveResume(sessionToken: string, resume: Resume): Promise<void>;
}
import type { Certification as _Certification, Education as _Education, Experience as _Experience, PersonalInfo as _PersonalInfo, Project as _Project, Resume as _Resume, Skill as _Skill, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async deleteResume(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async getResume(arg0: string): Promise<Resume> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return from_candid_Resume_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return from_candid_Resume_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveResume(arg0: string, arg1: Resume): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResume(arg0, to_candid_Resume_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResume(arg0, to_candid_Resume_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PersonalInfo_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalInfo): PersonalInfo {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Resume_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resume): Resume {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link: [] | [string];
    description: string;
    technologies: Array<string>;
}): {
    title: string;
    link?: string;
    description: string;
    technologies: Array<string>;
} {
    return {
        title: value.title,
        link: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.link)),
        description: value.description,
        technologies: value.technologies
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: [] | [string];
    name: string;
    photoUrl: [] | [string];
    email: string;
    summary: string;
    address: string;
    phone: string;
    github: [] | [string];
}): {
    linkedin?: string;
    name: string;
    photoUrl?: string;
    email: string;
    summary: string;
    address: string;
    phone: string;
    github?: string;
} {
    return {
        linkedin: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.linkedin)),
        name: value.name,
        photoUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.photoUrl)),
        email: value.email,
        summary: value.summary,
        address: value.address,
        phone: value.phone,
        github: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.github))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projects: Array<_Project>;
    createdAt: bigint;
    education: Array<_Education>;
    updatedAt: bigint;
    experiences: Array<_Experience>;
    certifications: Array<_Certification>;
    personalInfo: _PersonalInfo;
    skills: Array<_Skill>;
}): {
    projects: Array<Project>;
    createdAt: bigint;
    education: Array<Education>;
    updatedAt: bigint;
    experiences: Array<Experience>;
    certifications: Array<Certification>;
    personalInfo: PersonalInfo;
    skills: Array<Skill>;
} {
    return {
        projects: from_candid_vec_n10(_uploadFile, _downloadFile, value.projects),
        createdAt: value.createdAt,
        education: value.education,
        updatedAt: value.updatedAt,
        experiences: value.experiences,
        certifications: value.certifications,
        personalInfo: from_candid_PersonalInfo_n14(_uploadFile, _downloadFile, value.personalInfo),
        skills: value.skills
    };
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n11(_uploadFile, _downloadFile, x));
}
function to_candid_PersonalInfo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalInfo): _PersonalInfo {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Resume_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resume): _Resume {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projects: Array<Project>;
    createdAt: bigint;
    education: Array<Education>;
    updatedAt: bigint;
    experiences: Array<Experience>;
    certifications: Array<Certification>;
    personalInfo: PersonalInfo;
    skills: Array<Skill>;
}): {
    projects: Array<_Project>;
    createdAt: bigint;
    education: Array<_Education>;
    updatedAt: bigint;
    experiences: Array<_Experience>;
    certifications: Array<_Certification>;
    personalInfo: _PersonalInfo;
    skills: Array<_Skill>;
} {
    return {
        projects: to_candid_vec_n18(_uploadFile, _downloadFile, value.projects),
        createdAt: value.createdAt,
        education: value.education,
        updatedAt: value.updatedAt,
        experiences: value.experiences,
        certifications: value.certifications,
        personalInfo: to_candid_PersonalInfo_n21(_uploadFile, _downloadFile, value.personalInfo),
        skills: value.skills
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link?: string;
    description: string;
    technologies: Array<string>;
}): {
    title: string;
    link: [] | [string];
    description: string;
    technologies: Array<string>;
} {
    return {
        title: value.title,
        link: value.link ? candid_some(value.link) : candid_none(),
        description: value.description,
        technologies: value.technologies
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin?: string;
    name: string;
    photoUrl?: string;
    email: string;
    summary: string;
    address: string;
    phone: string;
    github?: string;
}): {
    linkedin: [] | [string];
    name: string;
    photoUrl: [] | [string];
    email: string;
    summary: string;
    address: string;
    phone: string;
    github: [] | [string];
} {
    return {
        linkedin: value.linkedin ? candid_some(value.linkedin) : candid_none(),
        name: value.name,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        email: value.email,
        summary: value.summary,
        address: value.address,
        phone: value.phone,
        github: value.github ? candid_some(value.github) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Project>): Array<_Project> {
    return value.map((x)=>to_candid_Project_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
