/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'issueDate' : string,
  'expiryDate' : string,
  'name' : string,
  'issuer' : string,
}
export interface Education {
  'major' : string,
  'institution' : string,
  'graduationYear' : string,
  'degree' : string,
}
export interface Experience {
  'endDate' : string,
  'description' : string,
  'company' : string,
  'jobTitle' : string,
  'startDate' : string,
}
export interface PersonalInfo {
  'linkedin' : [] | [string],
  'name' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'summary' : string,
  'address' : string,
  'phone' : string,
  'github' : [] | [string],
}
export interface Project {
  'title' : string,
  'link' : [] | [string],
  'description' : string,
  'technologies' : Array<string>,
}
export interface Resume {
  'projects' : Array<Project>,
  'createdAt' : bigint,
  'education' : Array<Education>,
  'updatedAt' : bigint,
  'experiences' : Array<Experience>,
  'certifications' : Array<Certification>,
  'personalInfo' : PersonalInfo,
  'skills' : Array<Skill>,
}
export interface Skill { 'name' : string, 'level' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteResume' : ActorMethod<[string], undefined>,
  'getResume' : ActorMethod<[string], Resume>,
  'saveResume' : ActorMethod<[string, Resume], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];