/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
});
export const Education = IDL.Record({
  'major' : IDL.Text,
  'institution' : IDL.Text,
  'graduationYear' : IDL.Text,
  'degree' : IDL.Text,
});
export const Experience = IDL.Record({
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Certification = IDL.Record({
  'issueDate' : IDL.Text,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'issuer' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'linkedin' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'summary' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'github' : IDL.Opt(IDL.Text),
});
export const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Text });
export const Resume = IDL.Record({
  'projects' : IDL.Vec(Project),
  'createdAt' : IDL.Int,
  'education' : IDL.Vec(Education),
  'updatedAt' : IDL.Int,
  'experiences' : IDL.Vec(Experience),
  'certifications' : IDL.Vec(Certification),
  'personalInfo' : PersonalInfo,
  'skills' : IDL.Vec(Skill),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteResume' : IDL.Func([IDL.Text], [], []),
  'getResume' : IDL.Func([IDL.Text], [Resume], ['query']),
  'saveResume' : IDL.Func([IDL.Text, Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
  });
  const Education = IDL.Record({
    'major' : IDL.Text,
    'institution' : IDL.Text,
    'graduationYear' : IDL.Text,
    'degree' : IDL.Text,
  });
  const Experience = IDL.Record({
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Certification = IDL.Record({
    'issueDate' : IDL.Text,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'issuer' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'linkedin' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'summary' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'github' : IDL.Opt(IDL.Text),
  });
  const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Text });
  const Resume = IDL.Record({
    'projects' : IDL.Vec(Project),
    'createdAt' : IDL.Int,
    'education' : IDL.Vec(Education),
    'updatedAt' : IDL.Int,
    'experiences' : IDL.Vec(Experience),
    'certifications' : IDL.Vec(Certification),
    'personalInfo' : PersonalInfo,
    'skills' : IDL.Vec(Skill),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteResume' : IDL.Func([IDL.Text], [], []),
    'getResume' : IDL.Func([IDL.Text], [Resume], ['query']),
    'saveResume' : IDL.Func([IDL.Text, Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };